### ISSUE TITLE
Improve the design report

### ISSUE THREAD

**Issue by ams316** [k8-proxy/p-design-requests#1]
Georgina González needs to  improve the design of this report
(https://glasswallsolu-qbp1117.slack.com/files/U01904REG23/F01B5DBRZ17/threatintelligencereport.pptx?origin_team=T016NMV79PD&origin_channel=C019S3W9UPLl)
Its assign to @Shashank S (Upwork Design)

**Comment by DGBREW** [comment]
Attached
[Threat Intelligence Report-v2.pdf](https://github.com/k8-proxy/p-design-requests/files/5233207/Threat.Intelligence.Report-v2.pdf)
[Threat Intelligence Report-v2.pptx](https://github.com/k8-proxy/p-design-requests/files/5233208/Threat.Intelligence.Report-v2.pptx)
